apiVersion: apps/v1
kind: Deployment
metadata:
  name: duatop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webduatop
  template:
    metadata:
      labels:
        app: webduatop
    spec:
      containers:
      - name: webduatop
        image: nguyenanhtu3101/duatopcicd:latest
        ports:
        - containerPort: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: duatop
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 7777
    nodePort: 31001
  selector:
    app: webduatop